services:
  temp-instance:
    image: mongo:7.0
    container_name: temp-instance
    env_file:
      - ../../.env
    volumes:
      - ./init-mongo-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'test', '-f', '/tmp/mongo-init/.init_done']
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      catalog_network:
        ipv4_address: 172.50.0.6
    depends_on:
      - catalog-mongo-primary
      - catalog-mongo-replica01
      - catalog-mongo-replica02

  catalog-mongo-primary:
    image: mongo:7.0
    container_name: catalog-mongo-primary
    volumes:
      - ${VOLUME_HOST_PATH}/m1:/data/db
      - ./keys/mongo-replica-set.key:/data/keyfile/mongo-replica-set.key:ro
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      catalog_network:
        ipv4_address: 172.50.0.2
    command:
      - '--replSet'
      - 'rs0'
      - '--keyFile'
      - '/data/keyfile/mongo-replica-set.key'

  catalog-mongo-replica01:
    image: mongo:7.0
    container_name: catalog-mongo-replica01
    volumes:
      - ${VOLUME_HOST_PATH}/m2:/data/db
      - ./keys/mongo-replica-set.key:/data/keyfile/mongo-replica-set.key:ro
    ports:
      - '27027:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      catalog_network:
        ipv4_address: 172.50.0.3
    command:
      - '--replSet'
      - 'rs0'
      - '--keyFile'
      - '/data/keyfile/mongo-replica-set.key'
    depends_on:
      - catalog-mongo-primary

  catalog-mongo-replica02:
    image: mongo:7.0
    container_name: catalog-mongo-replica02
    volumes:
      - ${VOLUME_HOST_PATH}/m3:/data/db
      - ./keys/mongo-replica-set.key:/data/keyfile/mongo-replica-set.key:ro
    ports:
      - '27037:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      catalog_network:
        ipv4_address: 172.50.0.4
    command:
      - '--replSet'
      - 'rs0'
      - '--keyFile'
      - '/data/keyfile/mongo-replica-set.key'
    depends_on:
      - catalog-mongo-primary
