openapi: "3.1.0"
info:
  title: BreizhSport Catalogue API
  version: "1.2"
  description: |-
    API Documentation for managing articles in the BreizhSport Catalogue

    Some useful links:
    - [Catalogue API repository](https://github.com/MAALSI23G1/CATALOGUE_API)
tags:
  - name: health
    description: Check if the service is alread online
  - name: catalogue
    description: Access to BreizhSport catalog API routes 
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /api/health:
    get:
      tags: 
        - health
      summary: Health check
      description: Returns a message confirming the service is running.
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to BreizhSport Catalogue Services

  /api/catalogue:
    get:
      tags: 
        - catalogue
      summary: Get articles
      description: Retrieves a list of articles with optional pagination.
      parameters:
        - name: offset
          in: query
          description: Offset for pagination
          required: false
          schema:
            type: integer
            example: 0
        - name: limit
          in: query
          description: Maximum number of articles to return
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: List of articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Articles fetched successfully
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'

    post:
      tags: 
        - catalogue
      summary: Create an article
      description: Creates a new article in the catalogue.
      requestBody:
        description: Article data to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        '200':
          description: Article created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Article created successfully
                  articleId:
                    type: string
                    example: 676ae821ee116faf788dc3fb

  /api/catalogue/quantity:
    put:
      tags: 
        - catalogue
      summary: Update article quantities
      description: Updates the quantities of multiple articles.
      requestBody:
        description: List of items to update
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/UpdateItem'
      responses:
        '200':
          description: Articles updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Articles updated successfully
                  articles:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: string
                          example: 672c9163d0bf87c46666a32e
                        quantity:
                          type: int
                          example: 98

components:
  schemas:
    Article:
      type: object
      properties:
        title:
          type: string
          example: Introduction à TypeScript
        description: 
          type: string
          example: "Un livre détaillé pour apprendre les bases et les concepts avancés de TypeScript."
        image:
          type: string
          example: "https://example.com/images/typescript-book.jpg"
        price: 
          type: int
          example: 30
        quantity:
          type: int
          example: 100
        brand:
          type: string
          example: FitTrack
        rating:
          type: float
          example: 4.7

    UpdateItem:
      type: object
      properties:
        orderId:
          type: string
          example: "123s4fq5a"
        items:
          type: array
          items: 
            type: object
            properties:
              articleId:
                type: string
                example: 672c9163d0bf87c46666a32e
              qteCmd:
                type: int
                example: 2
